# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 346094f5509059251e80c88c0f8b181029024fe99473cfa629ca5ebea48e23e0fcdd4e686b55feb9db025dcc7f68e0295c41a40120d10cfaf87ce92e07c44e3b

test:
  secret_key_base: 48a558340c08b2d30e61bf3f68d817bdf8a62dfea1fa5d171bdd7d48015ad2c714aad3460213f2031c27ceab8a283a23ec54e327a137a0bad94fac9a10d4797f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
